#DEPENDENCIES COULD BE OUT OF DATE.

[package]
name = "user/rojotemplate"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.4"
Component = "sleitnick/component@2.4.6"
Signal = "sleitnick/signal@1.2.1"
Timer = "sleitnick/timer@1.1.2"
cmdr = "evaera/cmdr@1.9.0"